### ISSUE TITLE
Archive PlanetEclipse Bugzilla component

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/planeteclipse.org#12]
We've migrated Planeteclipse.org to GitHub and we are now leveraging it's issue queue to manage issues and request.

I would like to archive the PlanetEclipse Bugzilla component: https://bugs.eclipse.org/bugs/buglist.cgi?component=PlanetEclipse.org&list_id=18902234&product=Community&resolution=---

I was able to close a few bugs and move the remaining ones to Github:
https://github.com/EclipseFdn/planeteclipse.org/issues

At this time, the Eclipse Bugzilla component for Planet Eclipse should be empty. The website, readme and wiki was updated to link to the Github issue.

**Comment by eclipsewebmaster** [comment]
Done
