### ISSUE TITLE
Please add https://ed-merks.blogspot.com/

### ISSUE THREAD

**Issue by merks** [EclipseFdn/planeteclipse.org#14]
**Blog RSS Feed URL:

https://ed-merks.blogspot.com/feeds/posts/default?alt=rss

**Author Name"
Ed Merks

**Why should we add this blog to planeteclipse.org?

It's about Eclipse things

** Profile Picture:

![merks](https://user-images.githubusercontent.com/208716/63930287-50e82c00-ca53-11e9-8f9e-4b8fcda1f5d8.png)

Please include my most recent post into the feed; not the older ones of course.

**Comment by mbarbero** [comment]
Your blog is already registered in https://planeteclipse.org/planet/

See https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/planet.ini#L223

**Comment by merks** [comment]
Sorry, I didn't notice it was in the inactive list. :-)

Thanks.
