### ISSUE TITLE
Eclipse Dirigible related Blog

### ISSUE THREAD

**Issue by delchev** [EclipseFdn/planeteclipse.org#15]
**Blog RSS Feed URL:
http://www.dirigible.io/feed.xml

**Author Name"
Eclipse Dirigible

**Why should we add this blog to planeteclipse.org?
This blog contains all the posts related to the Eclipse Dirigible project

** Profile Picture:
http://www.dirigible.io/img/logo/dirigible-logo-185.png

**Comment by chrisguindon** [comment]
Change was merge. Your blog posts should start showing in ~30 minutes.
