### ISSUE TITLE
Readme points to Gerrit

### ISSUE THREAD

**Issue by vogella** [EclipseFdn/planeteclipse.org#16]
Looks to me that you are using Github and not Gerrit. But the Readme still points to Gerrit:

## Developer resources

The project maintains the following source code repositories

* https://git.eclipse.org/r/#/admin/projects/planeteclipse.org/planeteclipse.org

Please update Readme.

**Comment by chrisguindon** [comment]
Done:
https://github.com/EclipseFdn/planeteclipse.org/commit/ebb7d29634c95d79f9ac26dfda2b6ff90f96c961

Thanks!
