### ISSUE TITLE
Host planeteclipse.org on Eclipse OpenShift cluster

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/planeteclipse.org#2]
I created this fork to allow us to host planeteclipse.org on our Openshift cluster.

This fork is highly inspired by the work that we did for jakartablogs.ee:
https://github.com/jakartaee/jakartablogs.ee

One of the problem that we still need to fix is that planeteclipse.org is hosted in a /planet/ sub-directory:

https://planeteclipse.org/planet/

**Comment by guw** [comment]
@chrisguindon Can we move it to the root and redirect `/planet` to the new `/`?

**Comment by chrisguindon** [comment]
That would be the easiest solution but my concerns is that some RSS feed readers might not be able to properly handle redirects.

**Comment by chrisguindon** [comment]
@mbarbero When should we plan on deploying planeteclipse.org on EF OpenShift? We will need to sync our effort since I will need to merge all missing commits from https://git.eclipse.org/c/planeteclipse.org/planeteclipse.org.git/

**Comment by mbarbero** [comment]
Everything is ready for going live. We just wait for the reverse proxy to redirect to the cluster instead of current website. Should be done by tomorrow.

**Comment by mbarbero** [comment]
Planet Eclipse is now served by this repo deployed on openshift. Whenever a change is push to master branch, a CI/CD job is triggered and the new planet eclipse image is automatically deployed.

**Comment by chrisguindon** [comment]
Sorry for the noise. I accidentally reopened the issue! 

Thanks for doing this @mbarbero
