### ISSUE TITLE
Add Brian King's Blog to Planet Eclipse

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/planeteclipse.org#25]
**Blog RSS Feed URL:
https://blogs.eclipse.org/blog/567/feed

**Author Name"
Brian King

**Why should we add this blog to planeteclipse.org?
I will be writing primarily about the ECD Tools Working Group. 

** Profile Picture:
https://blogs.eclipse.org/sites/default/files/styles/site_login_profile_thumbnail/public/profile_pictures/picture-567-1595865726.jpg

**Comment by chrisguindon** [comment]
@flora8984461 in order to make this change you need to do the following:

1. Add Brian to the list here: https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/planet.ini
2. add his picture here: https://github.com/EclipseFdn/planeteclipse.org/tree/master/planet/theme/authors
