### ISSUE TITLE
Add my new blog to PlanetEclipse and blogs.eclipse.org

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/planeteclipse.org#29]
Please don't remove my old blog.

**Blog RSS Feed URL:
https://blog.waynebeaton.ca/index.xml

**Author Name"
Wayne Beaton

**Why should we add this blog to planeteclipse.org?
Because I'm delightful.

** Profile Picture:
![ThisIsTheWay](https://user-images.githubusercontent.com/555569/103939324-9746a400-50f9-11eb-9618-0ddf8b65dabb.jpg)

**Comment by chrisguindon** [comment]
@waynebeaton I am getting 404 on articles listed in your RSS feed:

- http://eclipse.waynebeaton.ca/posts/opensource/level-playing-field/
- http://eclipse.waynebeaton.ca/posts/opensource/contribute/
- http://eclipse.waynebeaton.ca/posts/opensource/rules-of-engagement/

We should be able to add your website once that issue is sorted out!

P.S I am happy to see you migrate to Hugo!

**Comment by chrisguindon** [comment]
I am going to keep myself on the bug since I need to be involved for blogs.eclipse.org.

**Comment by waynebeaton** [comment]
Well that's embarrassing. I had the baseURL configured incorrectly from an earlier incarnation. Fixed.

Thanks for checking.

**Comment by chrisguindon** [comment]
Thanks @waynebeaton !

Are you still planning to blog from http://waynebeaton.wordpress.com/feed/? 

If you do, I will keep your feed in blogs/planet per your instructions but if you are not, we should remove it since that won't remove any of your existing posts.

**Comment by chrisguindon** [comment]
Final question @waynebeaton 

What are you expecting us to do with your picture if we keep your old feed?

Should we keep it there or replace it with the one you posted here?
https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/theme/authors/wayne.png

**Comment by chrisguindon** [comment]
@waynebeaton,

We were waiting for a response but in order to get this done, we will merge this as-is. Please open a new bug if you wish to use a new picture for your old blog!

**Comment by waynebeaton** [comment]
Just keep the picture. Or use the new one. I don't really care.

**Comment by chrisguindon** [comment]
I did not touch your old entry. We can deal with that separately.

**Comment by waynebeaton** [comment]
Just leave it. It's still got good stuff in it.
