### ISSUE TITLE
Remove Dockerfile

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/planeteclipse.org#3]
I created a temporary Dockerfile (https://github.com/EclipseFdn/planeteclipse.org/blob/master/Dockerfile) to run this website on a laptop. 

It would be preferable to use https://github.com/EclipseFdn/dockerfiles/tree/master/planet-venus since it's exactly what we will be using on production.

**Comment by mbarbero** [comment]
The dockerfile is still required. It derives from the planet-venus one though.
