### ISSUE TITLE
Planet only keeps 2 articles per feed

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/planeteclipse.org#37]
Due to the new_feed_option set to "2", the planet only keeps 2 articles from the same feed while it keeps articles from other feeds for over a year. While this was probably introduced for some spam protection, I do not see a good reason to keep this number so low. I therefore suggest to raise this limit, e.g. to 8 and I will create a PR.

**Comment by JonasHelming** [comment]
Based on a discussion with @chrisguindon , we decided on going up to 25 for now

**Comment by chrisguindon** [comment]
> Based on a discussion with @chrisguindon , we decided on going up to 25 for now

+1 We can re-visit if this becomes a problem.
