### ISSUE TITLE
Some Posts are not showing up in the XML Feed

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/planeteclipse.org#43]
WRT to these 2 posts:
https://blogs.eclipse.org/post/brian-king/getting-listed-cloud-devtools-blog
https://blogs.eclipse.org/post/paul-buck/coder-why-they-chose-open-vsx-registry

@chrisguindon 
The ecdtools website will be updated when this feed is updated https://planeteclipse.org/planet/ecdtools.xml
It's seems to be "broken". The timestamp of the last update is 2022-02-09T15:19:49Z
I am triggering a manual rebuild of the site. Can you open an issue against the planeteclipse project? I feel like we will need to investigate why this is not updating automatically.

[Brian King]
Sure, will do

[chrisguindon]
Actually, 2022-02-09T15:19:49Z is today. The file is being updated but your posts are not getting included for some reasons.

**Comment by chrisguindon** [comment]
We needed to configure blogs.eclipse.org to share tags in the category element. The changes are now live and I can both post on our website!
